name: Release

on:
  workflow_call:
    inputs:
      name:
        description: 'Name of the project to be released'
        required: true
        type: string
      path:
        description: 'Path of the project to be released'
        required: true
        type: string
      type:
        description: 'Release type of the project (debug/internal/production)'
        default: 'internal'
        type: string
      output-path:
        description: 'Path to get the APK file'
        required: true
        type: string
    secrets:
      project-id:
        description: 'WalletConnect Cloud ID'
        required: true
        type: string
      firebase-app-id:
        required: true
        type: string
      firebase-token:
        required: true
        type: string
      relay-url:
        description: 'WalletConnect Relay URL'
        required: false
        type: string
      sentry-dns:
        required: true
        type: string
      sentry-file:
        required: true
        type: string

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          architecture: x86_64
          cache: 'gradle'
  build:
    name: Build ${{ inputs.name }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.path }}
    steps:
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - run: touch .env.${{ inputs.type }} && echo "ENV_PROJECT_ID=${{ secrets.project-id }}\nENV_RELAY_URL=${{ secrets.relay-url }}\nENV_SENTRY_DSN=${{ secrets.sentry-dns }}\nENV_SENTRY_TAG==${{ inputs.type }}" >> .env.${{ inputs.type }}
      - run: touch ./android/sentry.properties && echo "${{ secrets.sentry-file }}" >> ./android/sentry.properties
      
      - name: Build APK
        run: yarn run android:build:internal
  
      - name: Setup Firebase
        uses: w9jds/setup-firebase@main
        with:
          tools-version: 13.0.1
          firebase_token: ${{ secrets.firebase-token }}
      
      - name: Upload APK
        env:
          APP_ID: ${{ secrets.firebase-app-id }}
        run: |
          firebase appdistribution:distribute ./android/app/build/outputs/apk/${{ inputs.output-path }} --app $APP_ID --release-notes "${{ inputs.name }} ${{ inputs.type }} release"
        